export const pokemons = [
  {
    pokeId: '001',
    name: 'Bulbasaur',
    type: ['grass', 'poison'],
    avatar: 'https://i.imgur.com/Qo3eNCH.png',
    checked: true,
  },
  {
    pokeId: '002',
    name: 'Ivysaur',
    type: ['grass', 'poison'],
    avatar: 'https://i.imgur.com/0lTgA23.png',
    checked: true,
  },
  {
    pokeId: '003',
    name: 'Venusaur',
    type: ['grass', 'poison'],
    avatar: 'https://i.imgur.com/vL013Za.png',
    checked: false,
  },
  {
    pokeId: '004',
    name: 'Charmander',
    type: ['fire'],
    avatar: 'https://i.imgur.com/Ra71R2U.png',
    checked: true,
  },
  {
    pokeId: '005',
    name: 'Charmeleon',
    type: ['fire'],
    avatar: 'https://i.imgur.com/1E3cqX5.png',
    checked: false,
  },
  {
    pokeId: '006',
    name: 'Charizard',
    type: ['fire', 'flying'],
    avatar: 'https://i.imgur.com/4ui1daR.png',
    checked: false,
  },
  {
    pokeId: '007',
    name: 'Squirtle',
    type: ['water'],
    avatar: 'https://i.imgur.com/AqNNwS3.png',
    checked: true,
  },
  {
    pokeId: '008',
    name: 'Wartortle',
    type: ['water'],
    avatar: 'https://i.imgur.com/V1ID6S5.png',
    checked: false,
  },
  {
    pokeId: '009',
    name: 'Blastoise',
    type: ['water'],
    avatar: 'https://i.imgur.com/EQBsJhm.png',
    checked: false,
  },
  {
    pokeId: '025',
    name: 'Pikachu',
    type: ['electric'],
    avatar: 'https://i.imgur.com/qmaKdXm.png',
    checked: true,
  },
  {
    pokeId: '026',
    name: 'Raichu',
    type: ['electric'],
    avatar: 'https://i.imgur.com/CbqQ4s5.png',
    checked: false,
  },
  {
    pokeId: '041',
    name: 'Zubat',
    type: ['poison', 'flying'],
    avatar: 'https://i.imgur.com/rnSDxWP.png',
    checked: false,
  },
  {
    pokeId: '042',
    name: 'Golbat',
    type: ['poison', 'flying'],
    avatar: 'https://i.imgur.com/ZWLdvbD.png',
    checked: true,
  },
  {
    pokeId: '052',
    name: 'Meowth',
    type: ['normal'],
    avatar: 'https://i.imgur.com/2XYT3GD.png',
    checked: true,
  },
  {
    pokeId: '054',
    name: 'Psyduck',
    type: ['water'],
    avatar: 'https://i.imgur.com/SJ2IGmP.png',
    checked: true,
  },
];
